/** Independent retrospective simulation for the vessel-allocation overview.
 * Units are vehicles. Source sales proxies are never asserted to be actual imports.
 */
export type VesselOverviewData = {
  snapshotDate: string;
  months: string[];
  weeklyWindow: { start: string; end: string; weeks: number };
  sources: string[];
  assumptions: string[];
  models: {
    model: string;
    brand: "丰田" | "雷克萨斯";
    supply: number;
    directOrders: number;
    authorizedOrders: number;
    directOrderShortage: number;
    authorizedOrderShortage: number;
    directDemand4Weeks: number;
    authorizedDemand4Weeks: number;
    directReplenishmentShortage: number;
    authorizedReplenishmentShortage: number;
    /** Vessel reservations let order shortages be checked without cross-channel netting. */
    directSupply: number;
    authorizedSupply: number;
    /** Store inventory only; VPC inventory is accounted for separately. */
    directStock: number;
    authorizedStock: number;
  }[];
  supplyHistory: { month: string; toyota: number; lexus: number }[];
  channels: {
    channel: "直营" | "授权";
    storeCount: number;
    orders: number;
    orderShortage: number;
    demand4Weeks: number;
    replenishmentShortage: number;
  }[];
  vpcs: { id: string; name: string; stock: number; monthlySales: number[] }[];
  regions: {
    id: string;
    name: string;
    stock: number;
    monthlySales: number[];
  }[];
  stores: {
    id: string;
    name: string;
    shortName: string;
    channel: "直营" | "授权";
    region: string;
    weeklySales: number;
    stock: number;
  }[];
  summary: {
    supply: number;
    toyotaSupply: number;
    lexusSupply: number;
    orders: number;
    orderShortage: number;
    demand4Weeks: number;
    replenishmentShortage: number;
    storeStock: number;
    vpcStock: number;
    /** Last representative vessel versus the preceding representative vessel, percent. */
    supplyChangePercent: number;
  };
};

export const vesselOverview: VesselOverviewData = {
  snapshotDate: "2026-08-05",
  months: [
    "2025-07",
    "2025-08",
    "2025-09",
    "2025-10",
    "2025-11",
    "2025-12",
    "2026-01",
    "2026-02",
    "2026-03",
    "2026-04",
    "2026-05",
    "2026-06",
    "2026-07",
  ],
  weeklyWindow: {
    start: "2026-06-08",
    end: "2026-08-02",
    weeks: 8,
  },
  sources: [
    "data/00_客户/门店主数据.csv — 模拟客户网络、门店编码、名称和地理大区",
    "data/01_供给/按月总表.csv — G/H销量代理及推估，仅参考模拟规模和趋势，非实际到港量",
    "data/01_供给/主流车型备注.csv — 车系组合参考，未核实次级车型数量不作为事实",
    "data/02_销速/周度门店销量.csv — 模拟周报及月报拆周，最新原始周截至2026-07-26",
    "data/02_销速/月度门店销量.csv — 按源门店映射汇总2025-07至2026-07月销量",
    "data/03_库存/当前库存_门店.csv — 仅参考库存结构；2026-09-29数量不用于本快照",
    "https://www.toyota.com.sa/en/sitemap",
    "https://www.toyota.com.sa/en/vehicles/prado",
    "https://www.toyota.com.sa/en/vehicles/rav4",
    "https://www.lexus.com.sa/en/vehicles/lx",
    "https://www.lexus.com.sa/en/vehicles/es",
    "https://www.lexus.com.sa/en/vehicles/rx",
    "https://www.lexus.com.sa/en/vehicles/nx",
    "https://toyota.jp/landcruiser300/",
    "https://www.marketscreener.com/news/toyota-motor-to-cut-output-for-middle-east-by-nearly-40-000-vehicles-nikkei-reports-ce7e5fdbda8ef322",
  ],
  assumptions: [
    "全部客户、订单、车型分摊和库存为模拟；源表于2026-09-29生成，本模块为历史情景回放重建2026-08-05状态，不声称数据当日已可获得。",
    "供给为模拟单船到港量；2025-07至2026-07每月一条代表船次，2026-07最后一期代表当前船次1800台，非全国月进口总量，亦非月销量。",
    "供给月历史参考01_供给的丰田销量代理/雷克萨斯销量推估趋势，但数量另设；销量代理非核实进口，Comtrade日本/泰国全品牌进口不得直接等同丰田或雷克萨斯。",
    "2026-03起丰田代表船次下降为霍尔木兹运输受扰的情景假设。Reuters 2026-03-05（MarketScreener转载）报道中东目的地减产约4万台只是背景，不证明沙特本船或具体车型的到港损失。",
    "Land Cruiser 300、Prado 250、RAV4 Hybrid及Lexus LX/NX为可能供给偏紧的模拟车系；沙特官方产品页用于确认车名，日本Land Cruiser暂停接单仅为海外供需背景，不据此认定沙特实际缺货。车型短缺数量均为模拟。",
    "门店周均销速取2026-06-08至2026-08-02的8个完整周。源周明细只到2026-07-26；2026-07-27至2026-08-02每店重建为此前4周合计/4，按四舍五入取整数，再和前7周合计/8。授权源周明细本身为月报拆周，非实测周报。",
    "四周需求按每店周均销速×4四舍五入到整数后汇总；车型及品牌需求用模拟车系份额按最大余数分摊，直营/授权总量不变。已承诺订单包含在未来四周销售需求中，不与四周需求相加。",
    "订单缺口=max(渠道车型已承诺订单-渠道车型本船预留量,0)，不跨车型或渠道抵销；本船供给虽有总体余量，少数高需求车系仍有2–4%的订单缺口。",
    "2026-08-05门店库存依据八周销速与1.15–3.10周覆盖假设独立重建，未复制2026-09-29库存、在途或冻结量。四周补库缺口=max(渠道车型四周需求-门店库存-渠道车型本船预留量,0)，订单不重复扣减。",
    "VPC库存为独立模拟、未分到门店的既有实物，当前船次尚未纳入VPC或门店库存；VPC库存单列不计入本次门店补库可用量，因此与门店库存互不重复。未建VIN、冻结和跨库调拨细目。",
    "区域与VPC月销是同一79店模拟销量的不同维度，不能相加。VPC覆盖映射假设为JED=西部+南部、DMM=东部、RUH=中部+北部；RUH为内陆处理点，其历史曲线非进口卸船量。",
    "预计可售卖周数=(本船供给+门店库存+VPC库存)/(未来4周销售需求/4)。三款主要车型按未来4周需求降序选择；VPC车型库存按需求占比、以最大余数法模拟分摊到整数台。假设本船与现有库存均可售，不另加未来到货；这是需求覆盖估算，不是实际售罄日期。",
    "summary.supplyChangePercent为2026-07与2026-06代表船次总供给环比，品牌合计口径一致。",
  ],
  models: [
    {
      model: "Camry",
      brand: "丰田",
      supply: 360,
      directSupply: 252,
      authorizedSupply: 108,
      directOrders: 230,
      authorizedOrders: 95,
      directOrderShortage: 0,
      authorizedOrderShortage: 0,
      directDemand4Weeks: 1266,
      directStock: 803,
      directReplenishmentShortage: 211,
      authorizedDemand4Weeks: 547,
      authorizedStock: 363,
      authorizedReplenishmentShortage: 76,
    },
    {
      model: "Yaris",
      brand: "丰田",
      supply: 300,
      directSupply: 210,
      authorizedSupply: 90,
      directOrders: 182,
      authorizedOrders: 75,
      directOrderShortage: 0,
      authorizedOrderShortage: 0,
      directDemand4Weeks: 978,
      directStock: 589,
      directReplenishmentShortage: 179,
      authorizedDemand4Weeks: 422,
      authorizedStock: 266,
      authorizedReplenishmentShortage: 66,
    },
    {
      model: "Hilux",
      brand: "丰田",
      supply: 220,
      directSupply: 154,
      authorizedSupply: 66,
      directOrders: 138,
      authorizedOrders: 59,
      directOrderShortage: 0,
      authorizedOrderShortage: 0,
      directDemand4Weeks: 748,
      directStock: 427,
      directReplenishmentShortage: 167,
      authorizedDemand4Weeks: 323,
      authorizedStock: 193,
      authorizedReplenishmentShortage: 64,
    },
    {
      model: "Corolla",
      brand: "丰田",
      supply: 180,
      directSupply: 126,
      authorizedSupply: 54,
      directOrders: 112,
      authorizedOrders: 48,
      directOrderShortage: 0,
      authorizedOrderShortage: 0,
      directDemand4Weeks: 691,
      directStock: 424,
      directReplenishmentShortage: 141,
      authorizedDemand4Weeks: 298,
      authorizedStock: 191,
      authorizedReplenishmentShortage: 53,
    },
    {
      model: "Land Cruiser 300",
      brand: "丰田",
      supply: 140,
      directSupply: 98,
      authorizedSupply: 42,
      directOrders: 108,
      authorizedOrders: 48,
      directOrderShortage: 10,
      authorizedOrderShortage: 6,
      directDemand4Weeks: 576,
      directStock: 174,
      directReplenishmentShortage: 304,
      authorizedDemand4Weeks: 248,
      authorizedStock: 78,
      authorizedReplenishmentShortage: 128,
    },
    {
      model: "Prado 250",
      brand: "丰田",
      supply: 110,
      directSupply: 77,
      authorizedSupply: 33,
      directOrders: 83,
      authorizedOrders: 37,
      directOrderShortage: 6,
      authorizedOrderShortage: 4,
      directDemand4Weeks: 518,
      directStock: 175,
      directReplenishmentShortage: 266,
      authorizedDemand4Weeks: 224,
      authorizedStock: 79,
      authorizedReplenishmentShortage: 112,
    },
    {
      model: "RAV4 Hybrid",
      brand: "丰田",
      supply: 100,
      directSupply: 70,
      authorizedSupply: 30,
      directOrders: 78,
      authorizedOrders: 34,
      directOrderShortage: 8,
      authorizedOrderShortage: 4,
      directDemand4Weeks: 460,
      directStock: 148,
      directReplenishmentShortage: 242,
      authorizedDemand4Weeks: 199,
      authorizedStock: 67,
      authorizedReplenishmentShortage: 102,
    },
    {
      model: "Fortuner",
      brand: "丰田",
      supply: 80,
      directSupply: 56,
      authorizedSupply: 24,
      directOrders: 50,
      authorizedOrders: 21,
      directOrderShortage: 0,
      authorizedOrderShortage: 0,
      directDemand4Weeks: 345,
      directStock: 170,
      directReplenishmentShortage: 119,
      authorizedDemand4Weeks: 149,
      authorizedStock: 77,
      authorizedReplenishmentShortage: 48,
    },
    {
      model: "Highlander",
      brand: "丰田",
      supply: 50,
      directSupply: 35,
      authorizedSupply: 15,
      directOrders: 29,
      authorizedOrders: 12,
      directOrderShortage: 0,
      authorizedOrderShortage: 0,
      directDemand4Weeks: 173,
      directStock: 93,
      directReplenishmentShortage: 45,
      authorizedDemand4Weeks: 75,
      authorizedStock: 42,
      authorizedReplenishmentShortage: 18,
    },
    {
      model: "Lexus LX 600",
      brand: "雷克萨斯",
      supply: 60,
      directSupply: 54,
      authorizedSupply: 6,
      directOrders: 60,
      authorizedOrders: 8,
      directOrderShortage: 6,
      authorizedOrderShortage: 2,
      directDemand4Weeks: 198,
      directStock: 64,
      directReplenishmentShortage: 80,
      authorizedDemand4Weeks: 22,
      authorizedStock: 7,
      authorizedReplenishmentShortage: 9,
    },
    {
      model: "Lexus ES 300h",
      brand: "雷克萨斯",
      supply: 80,
      directSupply: 72,
      authorizedSupply: 8,
      directOrders: 62,
      authorizedOrders: 7,
      directOrderShortage: 0,
      authorizedOrderShortage: 0,
      directDemand4Weeks: 269,
      directStock: 168,
      directReplenishmentShortage: 29,
      authorizedDemand4Weeks: 31,
      authorizedStock: 20,
      authorizedReplenishmentShortage: 3,
    },
    {
      model: "Lexus RX 350h",
      brand: "雷克萨斯",
      supply: 65,
      directSupply: 59,
      authorizedSupply: 6,
      directOrders: 52,
      authorizedOrders: 5,
      directOrderShortage: 0,
      authorizedOrderShortage: 0,
      directDemand4Weeks: 198,
      directStock: 111,
      directReplenishmentShortage: 28,
      authorizedDemand4Weeks: 22,
      authorizedStock: 13,
      authorizedReplenishmentShortage: 3,
    },
    {
      model: "Lexus NX 350h",
      brand: "雷克萨斯",
      supply: 55,
      directSupply: 50,
      authorizedSupply: 5,
      directOrders: 54,
      authorizedOrders: 7,
      directOrderShortage: 4,
      authorizedOrderShortage: 2,
      directDemand4Weeks: 127,
      directStock: 56,
      directReplenishmentShortage: 21,
      authorizedDemand4Weeks: 14,
      authorizedStock: 7,
      authorizedReplenishmentShortage: 2,
    },
  ],
  supplyHistory: [
    {
      month: "2025-07",
      toyota: 3850,
      lexus: 300,
    },
    {
      month: "2025-08",
      toyota: 4020,
      lexus: 310,
    },
    {
      month: "2025-09",
      toyota: 4100,
      lexus: 325,
    },
    {
      month: "2025-10",
      toyota: 4250,
      lexus: 330,
    },
    {
      month: "2025-11",
      toyota: 4200,
      lexus: 320,
    },
    {
      month: "2025-12",
      toyota: 4750,
      lexus: 345,
    },
    {
      month: "2026-01",
      toyota: 3500,
      lexus: 285,
    },
    {
      month: "2026-02",
      toyota: 3420,
      lexus: 280,
    },
    {
      month: "2026-03",
      toyota: 3000,
      lexus: 285,
    },
    {
      month: "2026-04",
      toyota: 2650,
      lexus: 275,
    },
    {
      month: "2026-05",
      toyota: 2230,
      lexus: 270,
    },
    {
      month: "2026-06",
      toyota: 1820,
      lexus: 265,
    },
    {
      month: "2026-07",
      toyota: 1540,
      lexus: 260,
    },
  ],
  channels: [
    {
      channel: "直营",
      storeCount: 34,
      orders: 1238,
      orderShortage: 34,
      demand4Weeks: 6547,
      replenishmentShortage: 1832,
    },
    {
      channel: "授权",
      storeCount: 45,
      orders: 456,
      orderShortage: 18,
      demand4Weeks: 2574,
      replenishmentShortage: 684,
    },
  ],
  vpcs: [
    {
      id: "JED",
      name: "吉达 VPC",
      stock: 420,
      monthlySales: [
        9813, 10663, 10687, 10916, 10693, 12488, 9012, 8807, 7524, 7155, 6091,
        5224, 4067,
      ],
    },
    {
      id: "DMM",
      name: "达曼 VPC",
      stock: 280,
      monthlySales: [
        4443, 4747, 4952, 5117, 4997, 5651, 4168, 3969, 3450, 3254, 2690, 2320,
        1824,
      ],
    },
    {
      id: "RUH",
      name: "利雅得 VPC",
      stock: 360,
      monthlySales: [
        7358, 7851, 7952, 8307, 8234, 9223, 6469, 6523, 5817, 5339, 4466, 3716,
        3010,
      ],
    },
  ],
  regions: [
    {
      id: "CENTRAL",
      name: "中部",
      stock: 1271,
      monthlySales: [
        6204, 6584, 6721, 6945, 6886, 7712, 5452, 5476, 4853, 4448, 3784, 3129,
        2554,
      ],
    },
    {
      id: "WEST",
      name: "西部",
      stock: 1544,
      monthlySales: [
        7461, 7937, 8132, 8180, 8031, 9309, 6778, 6581, 5652, 5401, 4584, 3938,
        3060,
      ],
    },
    {
      id: "EAST",
      name: "东部",
      stock: 1145,
      monthlySales: [
        4443, 4747, 4952, 5117, 4997, 5651, 4168, 3969, 3450, 3254, 2690, 2320,
        1824,
      ],
    },
    {
      id: "NORTH",
      name: "北部",
      stock: 239,
      monthlySales: [
        1154, 1267, 1231, 1362, 1348, 1511, 1017, 1047, 964, 891, 682, 587, 456,
      ],
    },
    {
      id: "SOUTH",
      name: "南部",
      stock: 606,
      monthlySales: [
        2352, 2726, 2555, 2736, 2662, 3179, 2234, 2226, 1872, 1754, 1507, 1286,
        1007,
      ],
    },
  ],
  stores: [
    {
      id: "MOCK-D-001",
      name: "模拟直营·利雅得·01店",
      shortName: "D01",
      channel: "直营",
      region: "中部",
      weeklySales: 89.0,
      stock: 102,
    },
    {
      id: "MOCK-D-008",
      name: "模拟直营·吉达·02店",
      shortName: "D08",
      channel: "直营",
      region: "西部",
      weeklySales: 79.125,
      stock: 138,
    },
    {
      id: "MOCK-D-009",
      name: "模拟直营·吉达·03店",
      shortName: "D09",
      channel: "直营",
      region: "西部",
      weeklySales: 71.0,
      stock: 82,
    },
    {
      id: "MOCK-D-007",
      name: "模拟直营·吉达·01店",
      shortName: "D07",
      channel: "直营",
      region: "西部",
      weeklySales: 68.75,
      stock: 213,
    },
    {
      id: "MOCK-D-015",
      name: "模拟直营·胡拜尔·01店",
      shortName: "D15",
      channel: "直营",
      region: "东部",
      weeklySales: 68.125,
      stock: 211,
    },
    {
      id: "MOCK-D-003",
      name: "模拟直营·利雅得·03店",
      shortName: "D03",
      channel: "直营",
      region: "中部",
      weeklySales: 64.75,
      stock: 126,
    },
    {
      id: "MOCK-D-019",
      name: "模拟直营·麦地那·01店",
      shortName: "D19",
      channel: "直营",
      region: "西部",
      weeklySales: 64.375,
      stock: 126,
    },
    {
      id: "MOCK-D-028",
      name: "模拟直营·艾卜哈·01店",
      shortName: "D28",
      channel: "直营",
      region: "南部",
      weeklySales: 61.25,
      stock: 141,
    },
    {
      id: "MOCK-D-002",
      name: "模拟直营·利雅得·02店",
      shortName: "D02",
      channel: "直营",
      region: "中部",
      weeklySales: 60.625,
      stock: 97,
    },
    {
      id: "MOCK-D-012",
      name: "模拟直营·达曼·01店",
      shortName: "D12",
      channel: "直营",
      region: "东部",
      weeklySales: 59.0,
      stock: 136,
    },
    {
      id: "MOCK-D-010",
      name: "模拟直营·吉达·04店",
      shortName: "D10",
      channel: "直营",
      region: "西部",
      weeklySales: 53.25,
      stock: 85,
    },
    {
      id: "MOCK-D-017",
      name: "模拟直营·麦加·01店",
      shortName: "D17",
      channel: "直营",
      region: "西部",
      weeklySales: 52.0,
      stock: 60,
    },
    {
      id: "MOCK-D-004",
      name: "模拟直营·利雅得·04店",
      shortName: "D04",
      channel: "直营",
      region: "中部",
      weeklySales: 50.625,
      stock: 116,
    },
    {
      id: "MOCK-D-013",
      name: "模拟直营·达曼·02店",
      shortName: "D13",
      channel: "直营",
      region: "东部",
      weeklySales: 47.0,
      stock: 120,
    },
    {
      id: "MOCK-D-005",
      name: "模拟直营·利雅得·05店",
      shortName: "D05",
      channel: "直营",
      region: "中部",
      weeklySales: 45.75,
      stock: 117,
    },
    {
      id: "MOCK-D-020",
      name: "模拟直营·麦地那·02店",
      shortName: "D20",
      channel: "直营",
      region: "西部",
      weeklySales: 44.75,
      stock: 103,
    },
    {
      id: "MOCK-D-014",
      name: "模拟直营·达曼·03店",
      shortName: "D14",
      channel: "直营",
      region: "东部",
      weeklySales: 43.625,
      stock: 124,
    },
    {
      id: "MOCK-D-022",
      name: "模拟直营·哈萨·01店",
      shortName: "D22",
      channel: "直营",
      region: "东部",
      weeklySales: 43.5,
      stock: 124,
    },
    {
      id: "MOCK-D-016",
      name: "模拟直营·胡拜尔·02店",
      shortName: "D16",
      channel: "直营",
      region: "东部",
      weeklySales: 41.75,
      stock: 73,
    },
    {
      id: "MOCK-D-011",
      name: "模拟直营·吉达·05店",
      shortName: "D11",
      channel: "直营",
      region: "西部",
      weeklySales: 41.125,
      stock: 80,
    },
    {
      id: "MOCK-D-027",
      name: "模拟直营·塔布克·01店",
      shortName: "D27",
      channel: "直营",
      region: "北部",
      weeklySales: 40.75,
      stock: 79,
    },
    {
      id: "MOCK-D-023",
      name: "模拟直营·布赖代·01店",
      shortName: "D23",
      channel: "直营",
      region: "中部",
      weeklySales: 39.75,
      stock: 123,
    },
    {
      id: "MOCK-D-024",
      name: "模拟直营·布赖代·02店",
      shortName: "D24",
      channel: "直营",
      region: "中部",
      weeklySales: 38.875,
      stock: 68,
    },
    {
      id: "MOCK-D-006",
      name: "模拟直营·利雅得·06店",
      shortName: "D06",
      channel: "直营",
      region: "中部",
      weeklySales: 37.375,
      stock: 107,
    },
    {
      id: "MOCK-D-029",
      name: "模拟直营·艾卜哈·02店",
      shortName: "D29",
      channel: "直营",
      region: "南部",
      weeklySales: 37.125,
      stock: 95,
    },
    {
      id: "MOCK-D-026",
      name: "模拟直营·哈伊勒·01店",
      shortName: "D26",
      channel: "直营",
      region: "北部",
      weeklySales: 37.0,
      stock: 59,
    },
    {
      id: "MOCK-D-018",
      name: "模拟直营·麦加·02店",
      shortName: "D18",
      channel: "直营",
      region: "西部",
      weeklySales: 36.875,
      stock: 59,
    },
    {
      id: "MOCK-D-034",
      name: "模拟直营·朱拜勒·01店",
      shortName: "D34",
      channel: "直营",
      region: "东部",
      weeklySales: 36.625,
      stock: 59,
    },
    {
      id: "MOCK-D-021",
      name: "模拟直营·塔伊夫·01店",
      shortName: "D21",
      channel: "直营",
      region: "西部",
      weeklySales: 36.5,
      stock: 93,
    },
    {
      id: "MOCK-D-025",
      name: "模拟直营·欧奈宰·01店",
      shortName: "D25",
      channel: "直营",
      region: "中部",
      weeklySales: 30.75,
      stock: 35,
    },
    {
      id: "MOCK-D-032",
      name: "模拟直营·奈季兰·01店",
      shortName: "D32",
      channel: "直营",
      region: "南部",
      weeklySales: 30.75,
      stock: 54,
    },
    {
      id: "MOCK-D-033",
      name: "模拟直营·延布·01店",
      shortName: "D33",
      channel: "直营",
      region: "西部",
      weeklySales: 28.5,
      stock: 33,
    },
    {
      id: "MOCK-D-030",
      name: "模拟直营·海米斯穆谢特·01店",
      shortName: "D30",
      channel: "直营",
      region: "南部",
      weeklySales: 28.25,
      stock: 81,
    },
    {
      id: "MOCK-D-031",
      name: "模拟直营·吉赞·01店",
      shortName: "D31",
      channel: "直营",
      region: "南部",
      weeklySales: 26.75,
      stock: 83,
    },
    {
      id: "MOCK-L2-010",
      name: "模拟二级展厅·吉达·02店",
      shortName: "A10",
      channel: "授权",
      region: "西部",
      weeklySales: 22.5,
      stock: 57,
    },
    {
      id: "MOCK-L2-004",
      name: "模拟二级展厅·利雅得·04店",
      shortName: "A04",
      channel: "授权",
      region: "中部",
      weeklySales: 20.375,
      stock: 63,
    },
    {
      id: "MOCK-L2-009",
      name: "模拟二级展厅·吉达·01店",
      shortName: "A09",
      channel: "授权",
      region: "西部",
      weeklySales: 19.375,
      stock: 45,
    },
    {
      id: "MOCK-L2-001",
      name: "模拟二级展厅·利雅得·01店",
      shortName: "A01",
      channel: "授权",
      region: "中部",
      weeklySales: 19.125,
      stock: 44,
    },
    {
      id: "MOCK-L2-019",
      name: "模拟二级展厅·胡拜尔·01店",
      shortName: "A19",
      channel: "授权",
      region: "东部",
      weeklySales: 18.5,
      stock: 53,
    },
    {
      id: "MOCK-L2-030",
      name: "模拟二级展厅·布赖代·01店",
      shortName: "A30",
      channel: "授权",
      region: "中部",
      weeklySales: 18.25,
      stock: 21,
    },
    {
      id: "MOCK-L2-013",
      name: "模拟二级展厅·吉达·05店",
      shortName: "A13",
      channel: "授权",
      region: "西部",
      weeklySales: 18.0,
      stock: 32,
    },
    {
      id: "MOCK-L2-006",
      name: "模拟二级展厅·利雅得·06店",
      shortName: "A06",
      channel: "授权",
      region: "中部",
      weeklySales: 17.875,
      stock: 21,
    },
    {
      id: "MOCK-L2-012",
      name: "模拟二级展厅·吉达·04店",
      shortName: "A12",
      channel: "授权",
      region: "西部",
      weeklySales: 17.5,
      stock: 54,
    },
    {
      id: "MOCK-L2-015",
      name: "模拟二级展厅·达曼·01店",
      shortName: "A15",
      channel: "授权",
      region: "东部",
      weeklySales: 15.875,
      stock: 25,
    },
    {
      id: "MOCK-L2-018",
      name: "模拟二级展厅·达曼·04店",
      shortName: "A18",
      channel: "授权",
      region: "东部",
      weeklySales: 15.75,
      stock: 40,
    },
    {
      id: "MOCK-L2-005",
      name: "模拟二级展厅·利雅得·05店",
      shortName: "A05",
      channel: "授权",
      region: "中部",
      weeklySales: 15.5,
      stock: 27,
    },
    {
      id: "MOCK-L2-025",
      name: "模拟二级展厅·麦地那·02店",
      shortName: "A25",
      channel: "授权",
      region: "西部",
      weeklySales: 15.375,
      stock: 35,
    },
    {
      id: "MOCK-L2-022",
      name: "模拟二级展厅·麦加·02店",
      shortName: "A22",
      channel: "授权",
      region: "西部",
      weeklySales: 15.25,
      stock: 18,
    },
    {
      id: "MOCK-L2-021",
      name: "模拟二级展厅·麦加·01店",
      shortName: "A21",
      channel: "授权",
      region: "西部",
      weeklySales: 15.125,
      stock: 26,
    },
    {
      id: "MOCK-L2-002",
      name: "模拟二级展厅·利雅得·02店",
      shortName: "A02",
      channel: "授权",
      region: "中部",
      weeklySales: 14.875,
      stock: 38,
    },
    {
      id: "MOCK-L2-017",
      name: "模拟二级展厅·达曼·03店",
      shortName: "A17",
      channel: "授权",
      region: "东部",
      weeklySales: 14.875,
      stock: 34,
    },
    {
      id: "MOCK-L2-020",
      name: "模拟二级展厅·胡拜尔·02店",
      shortName: "A20",
      channel: "授权",
      region: "东部",
      weeklySales: 14.875,
      stock: 46,
    },
    {
      id: "MOCK-L2-007",
      name: "模拟二级展厅·利雅得·07店",
      shortName: "A07",
      channel: "授权",
      region: "中部",
      weeklySales: 14.75,
      stock: 24,
    },
    {
      id: "MOCK-L2-024",
      name: "模拟二级展厅·麦地那·01店",
      shortName: "A24",
      channel: "授权",
      region: "西部",
      weeklySales: 14.75,
      stock: 29,
    },
    {
      id: "MOCK-L2-003",
      name: "模拟二级展厅·利雅得·03店",
      shortName: "A03",
      channel: "授权",
      region: "中部",
      weeklySales: 14.625,
      stock: 42,
    },
    {
      id: "MOCK-L2-032",
      name: "模拟二级展厅·布赖代·03店",
      shortName: "A32",
      channel: "授权",
      region: "中部",
      weeklySales: 13.875,
      stock: 27,
    },
    {
      id: "MOCK-L2-008",
      name: "模拟二级展厅·利雅得·08店",
      shortName: "A08",
      channel: "授权",
      region: "中部",
      weeklySales: 13.75,
      stock: 27,
    },
    {
      id: "MOCK-L2-041",
      name: "模拟二级展厅·吉赞·01店",
      shortName: "A41",
      channel: "授权",
      region: "南部",
      weeklySales: 13.75,
      stock: 32,
    },
    {
      id: "MOCK-L2-031",
      name: "模拟二级展厅·布赖代·02店",
      shortName: "A31",
      channel: "授权",
      region: "中部",
      weeklySales: 13.5,
      stock: 22,
    },
    {
      id: "MOCK-L2-011",
      name: "模拟二级展厅·吉达·03店",
      shortName: "A11",
      channel: "授权",
      region: "西部",
      weeklySales: 13.375,
      stock: 38,
    },
    {
      id: "MOCK-L2-014",
      name: "模拟二级展厅·吉达·06店",
      shortName: "A14",
      channel: "授权",
      region: "西部",
      weeklySales: 13.375,
      stock: 15,
    },
    {
      id: "MOCK-L2-039",
      name: "模拟二级展厅·艾卜哈·02店",
      shortName: "A39",
      channel: "授权",
      region: "南部",
      weeklySales: 13.125,
      stock: 21,
    },
    {
      id: "MOCK-L2-023",
      name: "模拟二级展厅·麦加·03店",
      shortName: "A23",
      channel: "授权",
      region: "西部",
      weeklySales: 12.875,
      stock: 21,
    },
    {
      id: "MOCK-L2-027",
      name: "模拟二级展厅·塔伊夫·02店",
      shortName: "A27",
      channel: "授权",
      region: "西部",
      weeklySales: 12.875,
      stock: 37,
    },
    {
      id: "MOCK-L2-016",
      name: "模拟二级展厅·达曼·02店",
      shortName: "A16",
      channel: "授权",
      region: "东部",
      weeklySales: 12.625,
      stock: 25,
    },
    {
      id: "MOCK-L2-042",
      name: "模拟二级展厅·吉赞·02店",
      shortName: "A42",
      channel: "授权",
      region: "南部",
      weeklySales: 12.625,
      stock: 32,
    },
    {
      id: "MOCK-L2-040",
      name: "模拟二级展厅·海米斯穆谢特·01店",
      shortName: "A40",
      channel: "授权",
      region: "南部",
      weeklySales: 12.5,
      stock: 24,
    },
    {
      id: "MOCK-L2-044",
      name: "模拟二级展厅·延布·01店",
      shortName: "A44",
      channel: "授权",
      region: "西部",
      weeklySales: 12.5,
      stock: 39,
    },
    {
      id: "MOCK-L2-038",
      name: "模拟二级展厅·艾卜哈·01店",
      shortName: "A38",
      channel: "授权",
      region: "南部",
      weeklySales: 12.125,
      stock: 14,
    },
    {
      id: "MOCK-L2-028",
      name: "模拟二级展厅·哈萨·01店",
      shortName: "A28",
      channel: "授权",
      region: "东部",
      weeklySales: 12.0,
      stock: 37,
    },
    {
      id: "MOCK-L2-034",
      name: "模拟二级展厅·哈伊勒·01店",
      shortName: "A34",
      channel: "授权",
      region: "北部",
      weeklySales: 11.625,
      stock: 30,
    },
    {
      id: "MOCK-L2-029",
      name: "模拟二级展厅·哈萨·02店",
      shortName: "A29",
      channel: "授权",
      region: "东部",
      weeklySales: 11.0,
      stock: 19,
    },
    {
      id: "MOCK-L2-045",
      name: "模拟二级展厅·朱拜勒·01店",
      shortName: "A45",
      channel: "授权",
      region: "东部",
      weeklySales: 11.0,
      stock: 19,
    },
    {
      id: "MOCK-L2-033",
      name: "模拟二级展厅·欧奈宰·01店",
      shortName: "A33",
      channel: "授权",
      region: "中部",
      weeklySales: 10.375,
      stock: 24,
    },
    {
      id: "MOCK-L2-026",
      name: "模拟二级展厅·塔伊夫·01店",
      shortName: "A26",
      channel: "授权",
      region: "西部",
      weeklySales: 10.125,
      stock: 26,
    },
    {
      id: "MOCK-L2-043",
      name: "模拟二级展厅·奈季兰·01店",
      shortName: "A43",
      channel: "授权",
      region: "南部",
      weeklySales: 10.125,
      stock: 29,
    },
    {
      id: "MOCK-L2-037",
      name: "模拟二级展厅·塔布克·02店",
      shortName: "A37",
      channel: "授权",
      region: "北部",
      weeklySales: 9.875,
      stock: 17,
    },
    {
      id: "MOCK-L2-035",
      name: "模拟二级展厅·哈伊勒·02店",
      shortName: "A35",
      channel: "授权",
      region: "北部",
      weeklySales: 9.25,
      stock: 26,
    },
    {
      id: "MOCK-L2-036",
      name: "模拟二级展厅·塔布克·01店",
      shortName: "A36",
      channel: "授权",
      region: "北部",
      weeklySales: 9.0,
      stock: 28,
    },
  ],
  summary: {
    supply: 1800,
    toyotaSupply: 1540,
    lexusSupply: 260,
    orders: 1694,
    orderShortage: 52,
    demand4Weeks: 9121,
    replenishmentShortage: 2516,
    storeStock: 4805,
    vpcStock: 1060,
    supplyChangePercent: -13.669064748201443,
  },
};

export function calculateVesselCoverage(data: VesselOverviewData) {
  const available =
    data.summary.supply + data.summary.storeStock + data.summary.vpcStock;
  const weeklyDemand = data.summary.demand4Weeks / 4;
  const modelDemand = data.models.reduce(
    (sum, model) =>
      sum + model.directDemand4Weeks + model.authorizedDemand4Weeks,
    0,
  );
  const models = data.models.map((model) => {
    const demand4Weeks =
      model.directDemand4Weeks + model.authorizedDemand4Weeks;
    const share =
      modelDemand > 0
        ? (data.summary.vpcStock * demand4Weeks) / modelDemand
        : 0;
    return {
      model: model.model,
      demand4Weeks,
      stock: model.directStock + model.authorizedStock,
      supply: model.supply,
      vpcStock: Math.floor(share),
      remainder: share - Math.floor(share),
    };
  });
  if (modelDemand > 0) {
    const remaining =
      data.summary.vpcStock -
      models.reduce((sum, model) => sum + model.vpcStock, 0);
    const byRemainder = [...models].sort(
      (a, b) => b.remainder - a.remainder || a.model.localeCompare(b.model),
    );
    for (let index = 0; index < remaining; index++)
      byRemainder[index].vpcStock++;
  }
  return {
    available,
    weeklyDemand,
    weeks: weeklyDemand > 0 ? available / weeklyDemand : null,
    models: models
      .sort(
        (a, b) =>
          b.demand4Weeks - a.demand4Weeks || a.model.localeCompare(b.model),
      )
      .map((model) => ({
        model: model.model,
        demand4Weeks: model.demand4Weeks,
        vpcStock: model.vpcStock,
        weeks:
          model.demand4Weeks > 0
            ? (model.supply + model.stock + model.vpcStock) /
              (model.demand4Weeks / 4)
            : null,
      })),
  };
}
